### ISSUE TITLE
How different from fold-to-ascii?

### ISSUE THREAD

**Issue by sandinmyjoints** [hunterwb/ascii-transliteration#12]
It could be useful to have a section in the README that describes how this project differs in behavior from https://www.npmjs.com/package/fold-to-ascii They seem similar in intent but I'm sure there are concrete differences (unless this is also based on Lucene ASCII Folding).

**Comment by hunterwb** [comment]
fold-to-ascii supports 1k different characters, only ones which are already similar to ascii characters.
anyascii supports 99k different characters from all languages.

https://github.com/mplatt/fold-to-ascii/blob/master/lib/ascii-folder.js
https://raw.githubusercontent.com/anyascii/anyascii/master/table.tsv
